name: Build Project and push to docker

on:
  push:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: api-version
      with:
        proj-path: ./komikaan/komikaan.csproj

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{steps.api-version.outputs.version}}',
            sha: context.sha
          })

    - name: Build and push api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: komikthuis/Dockerfile 
        pull: true
        push: true
        cache-from: type=registry,ref=enes1/komikaan:latest
        cache-to: type=inline
        tags: |
          enes1/komikaan:latest
          enes1/komikaan:${{steps.api-version.outputs.version}}
